### PR TITLE
UT: Reduce stack frame noise in crash dumps by scoping heavy objects

### LINKED ISSUE #1286: Misc: make sure intermediate local variables do not exist when broker task runs
The function where the main thread is blocked on broker run:
https://github.com/bloomberg/blazingmq/blob/a135d8e29d15f99c8fb18cf0f47c765e985575a2/src/applications/bmqbrkr/bmqbrkr.m.cpp#L753

If there is a crash, the main thread's stack traces in a debugger are flooded with unneeded local variables that take a lot of space.

A few candidates for simplification:

1. `balcl::OptionInfo specTable` super heavy and is not necessary during `run`.
We can control its lifetime by making a targeted scope with `{}`

```
{
   balcl::OptionInfo specTable...
   // do something with it
} // auto destructed on exiting the scope
```

2. `struct TaskEnvironment` contains a parsed configuration field `mqbcfg::Configuration d_config`

We don't need to keep it there and can have a temporary local variable that is destructed by the time we call `run`.

3. `m_bmqbrkr_task.h`: `class Task` contains a parsed configuration `const mqbcfg::TaskConfig& d_config` that is set in constructor. However, we don't need to cache this reference in class' fields, we can just pass config arg to `int Task::initialize(bsl::ostream& errorDescription);`. This is the only place where it is used.

See the attached screenshots with the examples of stack traces with long data fields that might be removed as a result of this refactoring:

Image

Image

Image

### PR DESCRIPTION
**Pull request by SrinathhSatuluri**
#1286

When the broker crashes during `run()`, the main thread's stack trace is
flooded with large local variables that are no longer needed, making
crash triage harder. This PR limits the lifetime of three heavy objects:

1. Wrap `specTable` and `commandLine` in a scoped block in `main()` so
  they destruct before `run()`.
2. Reset `d_config` in `TaskEnvironment` to a default-constructed state
  before entering `run()`.
3. Remove the cached `const mqbcfg::TaskConfig& d_config` member from
  `Task` and pass it as a parameter to `initialize()` instead, which is
  the only place it was used.

**Testing performed**

1. Verified the broker builds and starts successfully with all three
  changes applied.
2. Confirmed CLI argument parsing still works correctly after scoping
  `specTable`/`commandLine`.
3. Confirmed `Task::initialize()` receives and uses the config parameter
  identically to the previous cached reference.

closes: #1286

### CODE REVIEW

File: src/applications/bmqbrkr/m_bmqbrkr_task.h [hunk 1]
```diff
@@ -240,7 +236,8 @@ class Task {
 
     /// Create a new task, creating the pipe control channel in the
     /// specified `bmqPrefix` directory and using the specified `config`.
```
Comment (678098) [inline src/applications/bmqbrkr/m_bmqbrkr_task.h]:
```suggestion
    /// specified `bmqPrefix` directory.  Use the specified `allocatorType`
    /// for memory allocations.
```

The doc should also be updated to mention the new arg

File: src/applications/bmqbrkr/m_bmqbrkr_task.h [hunk 2]
```diff
@@ -253,7 +250,8 @@ class Task {
     /// description of the error.  The initialization leverages the
     /// properties from the `config` parameter supplied at construction of
     /// this object.
```
Comment (678098) [inline src/applications/bmqbrkr/m_bmqbrkr_task.h]:
```suggestion
/// properties from the `config` argument.
```

`config` is no longer supplied at construction, docs might be simplified

File: src/groups/bmq/bmqa/bmqa_closequeuestatus.t.cpp
Comment (678098) [inline src/groups/bmq/bmqa/bmqa_closequeuestatus.t.cpp:274]: The changes in this file are already merged in `main`, they should not be included in the PR's diff. This might happen if you based your latest commit on the previous non-main branch. Could you rebase your latest commit to remove these changes?

The simplest way that might work is pressing `Update with rebase` from GitHub Web UI for this PR

File: src/applications/bmqbrkr/bmqbrkr.m.cpp [hunk 3]
```diff
@@ -749,6 +754,9 @@ int main(int argc, const char* argv[])
         return mqbu::ExitCode::e_APP_INITIALIZE;  // RETURN
     }
 
+    // Clear the parsed configuration to reduce stack trace noise in crash
+    // dumps.  All needed values have already been extracted and applied.
+
```
Comment (678098) [inline src/applications/bmqbrkr/bmqbrkr.m.cpp]:
```suggestion
```

I think this comment is not necessary, because the behavior is visible from the code itself. There is also a small comment at line 670 that we can keep:

`}  // specTable and commandLine are destroyed here`

**Review by 678098 — COMMENTED** [review]
Looks good, just a few small comments about documentation

File: src/applications/bmqbrkr/m_bmqbrkr_task.h [hunk 4]
```diff
@@ -251,9 +249,9 @@ class Task {
     /// Initialize this object.  Return 0 on success and a non-zero value
     /// otherwise, populating the specified `errorDescription` with a
     /// description of the error.  The initialization leverages the
-    /// properties from the `config` parameter supplied at construction of
-    /// this object.
-    int initialize(bsl::ostream& errorDescription);
+/// properties from the `config` argument.
```
Comment (678098) [inline src/applications/bmqbrkr/m_bmqbrkr_task.h]:
```suggestion
    /// properties from the `config` argument.
```
Linter check

**Comment by SrinathhSatuluri** [comment]
Thank you for the feedback regarding the documentation @678098, and my apologies for basing the lastest commit on my previous branch.

**Review by 678098 — APPROVED** [review]
The PR looks good, let's wait for CI to pass and merge

**Comment by 678098** [comment]
Rebased the branch to get rid of UT failures.
The other failures are not related to this PR.

Looking closely at CI, it is almost fixed.

Only `taskEnv` takes a lot of space. Still can merge this PR as-is.
```
Thread 8 (Thread 0x7fd1c08a4780 (LWP 73179)):
  #0  0x00007fd1c0298d71 in __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffe10dd8170) at ./nptl/futex-internal.c:57
          sc_cancel_oldtype = 0
          sc_ret = <optimized out>
          resultvar = <optimized out>
          __arg6 = <optimized out>
          __arg5 = <optimized out>
          __arg4 = <optimized out>
          __arg3 = <optimized out>
          __arg2 = <optimized out>
          __arg1 = <optimized out>
          _a6 = <optimized out>
          _a5 = <optimized out>
          _a4 = <optimized out>
          _a3 = <optimized out>
          _a2 = <optimized out>
          _a1 = <optimized out>
  #1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x0, clockid=0, expected=0, futex_word=0x7ffe10dd8170) at ./nptl/futex-internal.c:87
          err = <optimized out>
          clockbit = 256
          op = 393
          err = <optimized out>
          clockbit = <optimized out>
          op = <optimized out>
  #2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7ffe10dd8170, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
  No locals.
  #3  0x00007fd1c02a4f1f in do_futex_wait (sem=sem@entry=0x7ffe10dd8170, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
          err = <optimized out>
  #4  0x00007fd1c02a4fb8 in __new_sem_wait_slow64 (sem=0x7ffe10dd8170, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
          _buffer = {__routine = 0x7fd1c02a4ef0 <__sem_wait_cleanup>, __arg = 0x7ffe10dd8170, __canceltype = 1165803712, __prev = 0x0}
          err = <optimized out>
          d = 0
  #5  0x000055b04431df5a in BloombergLP::bslmt::SemaphoreImpl<BloombergLP::bslmt::Platform::PosixSemaphore>::wait() ()
  No symbol table info available.
  #6  0x000055b0432930aa in BloombergLP::bslmt::Semaphore::wait (this=0x7ffe10dd8170) at /opt/bb/include/bslmt_semaphore.h:224
  No locals.
  #7  0x000055b04328e21c in run (errorDescription=..., taskEnv=0x7ffe10dd5ff0, wait=true) at /home/runner/work/blazingmq/blazingmq/src/applications/bmqbrkr/bmqbrkr.m.cpp:593
          localError = {<BloombergLP::bmqu::MemOutStream_BufferHolder> = {d_buffer = <incomplete type>}, <std::basic_ostream<char, std::char_traits<char> >> = {<No data fields>}, <No data fields>}
          rc = 0
  #8  0x000055b04328f44f in main (argc=2, argv=0x7ffe10dd82e8) at /home/runner/work/blazingmq/blazingmq/src/applications/bmqbrkr/bmqbrkr.m.cpp:758
          configDir = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "etc", '\000' <repeats 20 times>}}, d_start_p = 0x637465 <error: Cannot access memory at address 0x637465>}, d_length = 3, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}
          instanceId = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "default", '\000' <repeats 16 times>}}, d_start_p = 0x746c7561666564 <error: Cannot access memory at address 0x746c7561666564>}, d_length = 7, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}
          hostName = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = '\000' <repeats 23 times>}}, d_start_p = 0x0}, d_length = 0, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}
          hostTags = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = '\000' <repeats 23 times>}}, d_start_p = 0x0}, d_length = 0, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}
          hostDataCenter = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = '\000' <repeats 23 times>}}, d_start_p = 0x0}, d_length = 0, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}
          port = 0
          version = false
          sa = {__sigaction_handler = {sa_handler = 0x55b04328b8bc <appShutdownSignal(int)>, sa_sigaction = 0x55b04328b8bc <appShutdownSignal(int)>}, sa_mask = {__val = {0, 0, 0, 0, 0, 0, 0, 94215568435792, 0, 0, 0, 0, 0, 0, 0, 0}}, sa_flags = 0, sa_restorer = 0x0}
          rc = 0
          taskEnv = {d_instanceId = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "default", '\000' <repeats 16 times>}}, d_start_p = 0x746c7561666564 <error: Cannot access memory at address 0x746c7561666564>}, d_length = 7, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_bmqPrefix = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "./", '\000' <repeats 21 times>}}, d_start_p = 0x2f2e <error: Cannot access memory at address 0x2f2e>}, d_length = 2, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_configJson = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "\240\vm\\\260U", '\000' <repeats 17 times>}}, d_start_p = 0x55b05c6d0ba0 "{\n    \"taskConfig\": {\n        \"allocatorType\": \"COUNTING\",\n        \"allocationLimit\": 34359738368,\n        \"logController\": {\n", ' ' <repeats 12 times>, "\"fileName\": \"logs/logs.%T.%p\",\n", ' ' <repeats 12 times>, "\"fileMaxAgeDays\": 1"...}, d_length = 3452, d_capacity = 3452}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_config = {d_taskConfig = {d_allocationLimit = 34359738368, d_logController = {d_categories = {<bsl::vectorBase<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > >> = {d_dataBegin_p = 0x55b05c6ca990, d_dataEnd_p = 0x55b05c6ca9c0, d_capacity = 1}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > > >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > > >> = {d_allocator = {<std::pmr::polymorphic_allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > >> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_fileName = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "logs/logs.%T.%p\000\000\000\000\000\000\000\000"}}, d_start_p = 0x676f6c2f73676f6c <error: Cannot access memory at address 0x676f6c2f73676f6c>}, d_length = 15, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_logfileFormat = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "%d (%t) %s %F:%l %m\n\n\000\000"}}, d_start_p = 0x2029742528206425 <error: Cannot access memory at address 0x2029742528206425>}, d_length = 21, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_consoleFormat = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "\020\271l\\\260U\000\000\000\000\000\000\000\000\000\000\027\000\000\000\000\000\000"}}, d_start_p = 0x55b05c6cb910 "%c~@~%d~@~%t~@~%s~@~%F:%l~@~%m\\n"}, d_length = 32, d_capacity = 34}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_loggingVerbosity = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "INFO\000\000\000\000\f\000\000\000\000\000\000\000\027\000\000\000\000\000\000"}}, d_start_p = 0x4f464e49 <error: Cannot access memory at address 0x4f464e49>}, d_length = 4, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_bslsLogSeverityThreshold = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "ERROR\000\000\000\n\000\000\000\000\000\000\000\027\000\000\000\000\000\000"}}, d_start_p = 0x524f525245 <error: Cannot access memory at address 0x524f525245>}, d_length = 5, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_consoleSeverityThreshold = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "INFO\000\000\000\000+\000\000\000\000\000\000\000+\000\000\000\000\000\000"}}, d_start_p = 0x4f464e49 <error: Cannot access memory at address 0x4f464e49>}, d_length = 4, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_syslog = {d_appName = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "BMQ\000\000\000\000\000\200\372|E\260U\000\000 \270l\\\260U\000"}}, d_start_p = 0x514d42 <error: Cannot access memory at address 0x514d42>}, d_length = 3, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_logFormat = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "%d (%t) %s %F:%l %m\n\n\000\000"}}, d_start_p = 0x2029742528206425 <error: Cannot access memory at address 0x2029742528206425>}, d_length = 21, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_verbosity = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = '\000' <repeats 23 times>}}, d_start_p = 0x0}, d_length = 0, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_enabled = false, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb87d2 "enabled", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 1, d_name_p = 0x55b044bb8b1e "appName", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 2, d_name_p = 0x55b044bb8b26 "logFormat", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 3, d_name_p = 0x55b044bb8b30 "verbosity", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}}}, d_logDump = {d_recordingLevel = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "OFF\000\000\000\000\000me", '\000' <repeats 13 times>}}, d_start_p = 0x46464f <error: Cannot access memory at address 0x46464f>}, d_length = 3, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_triggerLevel = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "OFF", '\000' <repeats 20 times>}}, d_start_p = 0x46464f <error: Cannot access memory at address 0x46464f>}, d_length = 3, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_recordBufferSize = 32768, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb84ec "recordBufferSize", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 1, d_name_p = 0x55b044bb84fd "recordingLevel", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 2, d_name_p = 0x55b044bb850c "triggerLevel", d_nameLength = 12, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}}}, d_fileMaxAgeDays = 10, d_rotationBytes = 268435456, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb8cbc "fileName", d_nameLength = 8, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 1, d_name_p = 0x55b044bb8cc5 "fileMaxAgeDays", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 2, d_name_p = 0x55b044bb8cd4 "rotationBytes", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 3, d_name_p = 0x55b044bb8ce2 "logfileFormat", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 4, d_name_p = 0x55b044bb8cf0 "consoleFormat", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 5, d_name_p = 0x55b044bb8cfe "loggingVerbosity", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 6, d_name_p = 0x55b044bb8d0f "bslsLogSeverityThreshold", d_nameLength = 24, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 7, d_name_p = 0x55b044bb8d28 "consoleSeverityThreshold", d_nameLength = 24, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 8, d_name_p = 0x55b044bb8d41 "categories", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 9, d_name_p = 0x55b044bb8d4c "syslog", d_nameLength = 6, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 10, d_name_p = 0x55b044bb8d53 "logDump", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_allocatorType = BloombergLP::mqbcfg::AllocatorType::COUNTING, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb9173 "allocatorType", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 1, d_name_p = 0x55b044bb9181 "allocationLimit", d_nameLength = 15, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 2, d_name_p = 0x55b044bb9191 "logController", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_appConfig = {d_brokerInstanceName = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "\000\000\000\000\000\000\000\000\027\000\000\000\000\000\000\000P*}E\260U\000"}}, d_start_p = 0x0}, d_length = 0, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_etcDir = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "etc\000\000\000\000\000P\270l\\\260U\000\000P*}E\260U\000"}}, d_start_p = 0x637465 <error: Cannot access memory at address 0x637465>}, d_length = 3, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_hostName = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "east1", '\000' <repeats 18 times>}}, d_start_p = 0x3174736165 <error: Cannot access memory at address 0x3174736165>}, d_length = 5, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_hostTags = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = '\000' <repeats 23 times>}}, d_start_p = 0x0}, d_length = 0, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_hostDataCenter = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "east\000\000\000\000gs", '\000' <repeats 13 times>}}, d_start_p = 0x74736165 <error: Cannot access memory at address 0x74736165>}, d_length = 4, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_latencyMonitorDomain = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "bmq.sys.latemon.latency"}}, d_start_p = 0x2e7379732e716d62 <error: Cannot access memory at address 0x2e7379732e716d62>}, d_length = 23, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_tlsConfig = {<bsl::optional<BloombergLP::mqbcfg::TlsConfig>> = {<BloombergLP::bslstl::Optional_Base<BloombergLP::mqbcfg::TlsConfig, true>> = {d_value = {<BloombergLP::bslstl::Optional_DataImp<BloombergLP::mqbcfg::TlsConfig>> = {d_buffer = {d_buffer = "Override host tags\000\000\000\000\000\000\022\000\000\000\000\000\000\000\027\000\000\000\000\000\000\000P*}E\260U\000\000\006\000\000\000\000\000\000\000\000\\\335\020\376\177\000\000\000\000\000\000\000\000\000\000\200\372|E\260U\000\000\200\270l\\\260U\000\000P*}E\260U", '\000' <repeats 66 times>, "P*}E\260U", '\000' <repeats 25 times>, d_align = {d_c = "Override"}}, d_hasValue = false}, <No data fields>}, d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_stats = {d_plugins = {<bsl::vectorBase<BloombergLP::mqbcfg::StatPluginConfig>> = {d_dataBegin_p = 0x0, d_dataEnd_p = 0x0, d_capacity = 0}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<BloombergLP::mqbcfg::StatPluginConfig> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<BloombergLP::mqbcfg::StatPluginConfig> >> = {d_allocator = {<std::pmr::polymorphic_allocator<BloombergLP::mqbcfg::StatPluginConfig>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_printer = {d_file = {<bsl::String_Imp<char, unsigned long>> = {{d_short = {d_data = {d_buffer = "logs/stat.%T.%p\000P*}E\260U\000"}}, d_start_p = 0x6174732f73676f6c <error: Cannot access memory at address 0x6174732f73676f6c>}, d_length = 15, d_capacity = 23}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<char> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<char> >> = {d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, static npos = 18446744073709551615}, d_printInterval = 60, d_maxAgeDays = 3, d_rotateBytes = 268435456, d_rotateDays = 1, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb8980 "printInterval", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 1, d_name_p = 0x55b044bb898e "file", d_nameLength = 4, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 2, d_name_p = 0x55b044bb8993 "maxAgeDays", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 3, d_name_p = 0x55b044bb899e "rotateBytes", d_nameLength = 11, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 4, d_name_p = 0x55b044bb89aa "rotateDays", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}}}, d_snapshotInterval = 1, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb9300 "snapshotInterval", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 1, d_name_p = 0x55b044bb9311 "plugins", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 2, d_name_p = 0x55b044bb9319 "printer", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_plugins = {d_libraries = {<bsl::vectorBase<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > >> = {d_dataBegin_p = 0x0, d_dataEnd_p = 0x0, d_capacity = 0}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > > >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > > >> = {d_allocator = {<std::pmr::polymorphic_allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > >> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_enabled = {<bsl::vectorBase<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > >> = {d_dataBegin_p = 0x0, d_dataEnd_p = 0x0, d_capacity = 0}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > > >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > > >> = {d_allocator = {<std::pmr::polymorphic_allocator<bsl::basic_string<char, std::char_traits<char>, bsl::allocator<char> > >> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb87c8 "libraries", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 1, d_name_p = 0x55b044bb87d2 "enabled", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}}}, d_networkInterfaces = {d_tcpInterface = {<bsl::optional<BloombergLP::mqbcfg::TcpInterfaceConfig>> = {<BloombergLP::bslstl::Optional_Base<BloombergLP::mqbcfg::TcpInterfaceConfig, true>> = {d_value = {<BloombergLP::bslstl::Optional_DataImp<BloombergLP::mqbcfg::TcpInterfaceConfig>> = {d_buffer = {d_buffer = "\000\000@\000\000\000\000\000\000\000\000@\000\000\000\000\000\000P\000\000\000\000\000\000\000\000@", '\000' <repeats 28 times>, "P*}E\260U\000\000localhost", '\000' <repeats 15 times>, "\t\000\000\000\000\000\000\000\027\000\000\000\000\000\000\000P*}E\260U\000\000=\231\000\000\004\000\000\000\020'\000\000\270\v\000", d_align = {d_c = "\000\000@\000\000\000\000"}}, d_hasValue = true}, <No data fields>}, d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_heartbeats = {d_client = 10, d_downstreamBroker = 10, d_upstreamBroker = 10, d_clusterPeer = 10, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb849c "client", d_nameLength = 6, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 1, d_name_p = 0x55b044bb84a3 "downstreamBroker", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 2, d_name_p = 0x55b044bb84b4 "upstreamBroker", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 3, d_name_p = 0x55b044bb84c3 "clusterPeer", d_nameLength = 11, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}}}, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb9092 "heartbeats", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 1, d_name_p = 0x55b044bb909d "tcpInterface", d_nameLength = 12, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_messagePropertiesV2 = {d_minCppSdkVersion = 11207, d_minJavaSdkVersion = 10, d_advertiseV2Support = true, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb8590 "advertiseV2Support", d_nameLength = 18, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 1, d_name_p = 0x55b044bb85a3 "minCppSdkVersion", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 2, d_name_p = 0x55b044bb85b4 "minJavaSdkVersion", d_nameLength = 17, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}}}, d_dispatcherConfig = {d_sessions = {d_processorConfig = {d_queueSize = 500000, d_queueSizeLowWatermark = 100, d_queueSizeHighWatermark = 200000, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb830e "queueSize", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 1, d_name_p = 0x55b044bb8318 "queueSizeLowWatermark", d_nameLength = 21, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 2, d_name_p = 0x55b044bb832e "queueSizeHighWatermark", d_nameLength = 22, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}}}, d_numProcessors = 4, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb8c8a "numProcessors", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 1, d_name_p = 0x55b044bb8c98 "processorConfig", d_nameLength = 15, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_queues = {d_processorConfig = {d_queueSize = 500000, d_queueSizeLowWatermark = 100, d_queueSizeHighWatermark = 200000, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb830e "queueSize", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 1, d_name_p = 0x55b044bb8318 "queueSizeLowWatermark", d_nameLength = 21, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 2, d_name_p = 0x55b044bb832e "queueSizeHighWatermark", d_nameLength = 22, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}}}, d_numProcessors = 8, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb8c8a "numProcessors", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 1, d_name_p = 0x55b044bb8c98 "processorConfig", d_nameLength = 15, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_clusters = {d_processorConfig = {d_queueSize = 500000, d_queueSizeLowWatermark = 100, d_queueSizeHighWatermark = 200000, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb830e "queueSize", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 1, d_name_p = 0x55b044bb8318 "queueSizeLowWatermark", d_nameLength = 21, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 2, d_name_p = 0x55b044bb832e "queueSizeHighWatermark", d_nameLength = 22, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}}}, d_numProcessors = 4, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb8c8a "numProcessors", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 1, d_name_p = 0x55b044bb8c98 "processorConfig", d_nameLength = 15, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_alarmTimeoutMs = 180000, d_warningTimeoutMs = 10000, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb902c "sessions", d_nameLength = 8, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 1, d_name_p = 0x55b044bb9035 "queues", d_nameLength = 6, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 2, d_name_p = 0x55b044bb903c "clusters", d_nameLength = 8, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 3, d_name_p = 0x55b044bb9045 "alarmTimeoutMs", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 4, d_name_p = 0x55b044bb9054 "warningTimeoutMs", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}}}, d_bmqconfConfig = {d_cacheTTLSeconds = 30, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb80de "cacheTTLSeconds", d_nameLength = 15, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}}}, d_authentication = {d_authenticators = {<bsl::vectorBase<BloombergLP::mqbcfg::AuthenticatorPluginConfig>> = {d_dataBegin_p = 0x0, d_dataEnd_p = 0x0, d_capacity = 0}, <BloombergLP::bslalg::ContainerBase<bsl::allocator<BloombergLP::mqbcfg::AuthenticatorPluginConfig> >> = {<BloombergLP::bslalg::ContainerBase_NonEmptyBase<bsl::allocator<BloombergLP::mqbcfg::AuthenticatorPluginConfig> >> = {d_allocator = {<std::pmr::polymorphic_allocator<BloombergLP::mqbcfg::AuthenticatorPluginConfig>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_anonymousCredential = {<bsl::optional<BloombergLP::mqbcfg::AnonymousCredential>> = {<BloombergLP::bslstl::Optional_Base<BloombergLP::mqbcfg::AnonymousCredential, true>> = {d_value = {<BloombergLP::bslstl::Optional_DataImp<BloombergLP::mqbcfg::AnonymousCredential>> = {d_buffer = {d_buffer = "\000\000\000\000\000\000\000\000\r\000\000\000\000\000\000\000\027\000\000\000\000\000\000\000P*}E\260U\000\000\003\000\000\000\000\000\000\000hW\335\020\376\177", '\000' <repeats 11 times>, "\374|E\260U\000\000\020\271l\\\260U\000\000P*}E\260U", '\000' <repeats 33 times>, d_align = {d_c = "\000\000\000\000\000\000\000"}}, d_hasValue = false}, <No data fields>}, d_allocator = {<std::pmr::polymorphic_allocator<char>> = {_M_resource = 0x55b0457d2a50 <BloombergLP::g_newDeleteAllocatorSingleton>}, <No data fields>}}, <No data fields>}, <No data fields>}, d_minThreads = 1, d_maxThreads = 8, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb91bc "authenticators", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 1, d_name_p = 0x55b044bb91cb "anonymousCredential", d_nameLength = 19, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 2, d_name_p = 0x55b044bb91df "minThreads", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 3, d_name_p = 0x55b044bb91ea "maxThreads", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}}}, d_brokerVersion = 999999, d_configVersion = 999999, d_logsObserverMaxSize = 1000, d_routeCommandTimeoutMs = 3000, d_configureStream = false, d_advertiseSubscriptions = false, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb9360 "brokerInstanceName", d_nameLength = 18, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 1, d_name_p = 0x55b044bb9373 "brokerVersion", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 2, d_name_p = 0x55b044bb9381 "configVersion", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 3, d_name_p = 0x55b044bb938f "etcDir", d_nameLength = 6, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 4, d_name_p = 0x55b044bb9396 "hostName", d_nameLength = 8, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 5, d_name_p = 0x55b044bb939f "hostTags", d_nameLength = 8, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 6, d_name_p = 0x55b044bb93a8 "hostDataCenter", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 4}, {d_id = 7, d_name_p = 0x55b044bb93b7 "logsObserverMaxSize", d_nameLength = 19, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 1}, {d_id = 8, d_name_p = 0x55b044bb93cb "latencyMonitorDomain", d_nameLength = 20, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 9, d_name_p = 0x55b044bb93e0 "dispatcherConfig", d_nameLength = 16, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 10, d_name_p = 0x55b044bb93f1 "stats", d_nameLength = 5, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 11, d_name_p = 0x55b044bb93f7 "networkInterfaces", d_nameLength = 17, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 12, d_name_p = 0x55b044bb9409 "bmqconfConfig", d_nameLength = 13, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 13, d_name_p = 0x55b044bb9311 "plugins", d_nameLength = 7, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 14, d_name_p = 0x55b044bb9417 "messagePropertiesV2", d_nameLength = 19, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 15, d_name_p = 0x55b044bb942b "configureStream", d_nameLength = 15, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 16, d_name_p = 0x55b044bb943b "advertiseSubscriptions", d_nameLength = 22, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097156}, {d_id = 17, d_name_p = 0x55b044bb9452 "routeCommandTimeoutMs", d_nameLength = 21, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 2097153}, {d_id = 18, d_name_p = 0x55b044bb9468 "authentication", d_nameLength = 14, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 19, d_name_p = 0x55b044bb9477 "tlsConfig", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, static ATTRIBUTE_INFO_ARRAY = {{d_id = 0, d_name_p = 0x55b044bb952e "taskConfig", d_nameLength = 10, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}, {d_id = 1, d_name_p = 0x55b044bb9539 "appConfig", d_nameLength = 9, d_annotation_p = 0x55b044bb8030 "", d_formattingMode = 0}}}, d_task = {d_buffer = "\001", '\000' <repeats 111 times>, "\270=wE\260U\000\000cP\236O", '\000' <repeats 12 times>, "\377\377\377\377\377\377\377\377", '\000' <repeats 48 times>, ")\340\307D\260U\000\000"..., d_align = {d_c = "\001", '\000' <repeats 14 times>}}, d_app = {d_buffer = "\220{\335\020\376\177\000\000P\021n\\\260U\000\000\300Xo\\\260U\000\0008Zo\\\260U\000\000\020\000\000\000\321\177\000\000\360\253r\\\260U\000\000\r\000\000\000\000\000\000\000`Yo\\\260U\000\000\f\000\000\000\000\000\000\000\r\000\000\000\000\000\000\000\000\000\200?\000\000\000\000\000\000\000\000\321\177\000\000P\021n\\\260U\000\000\260h\335\020\376\177\000\000\200\026n\\\260U\000\000\005\000\000\000\000\000\000\000\220\026n\\\260U\000\000\300*n\\\260U\000\000\220\026n\\\260U\000\000\300*n\\\260U\000\000P\021n\\\260U", '\000' <repeats 94 times>..., d_align = {d_c = "\220{\335\020\376\177\000\000P\021n\\\260U\000"}}, d_shutdownSemaphore = {d_impl = {d_sem = {__size = "\000\000\000\000\001\000\000\000\000\000\000\000\260U\000\000\300%}E\260U\000\000\031\210$\300\321\177\000", __align = 4294967296}}}}
          prefixEnvVar = 0x0
          errorDescription = {<BloombergLP::bmqu::MemOutStream_BufferHolder> = {d_buffer = <incomplete type>}, <std::basic_ostream<char, std::char_traits<char> >> = {<No data fields>}, <No data fields>}
  
```

**Comment by SrinathhSatuluri** [comment]
Regarding taskEnv still taking a lot of space, would you like me to address that in this PR before merging, or should we track it as a separate follow-up issue?

**Comment by SrinathhSatuluri** [comment]
Rebased onto latest main and squashed into a single signed-off commit.

File: src/applications/bmqbrkr/bmqbrkr.m.cpp [hunk 5]
```diff
@@ -605,64 +608,66 @@ int main(int argc, const char* argv[])
...
-        bsl::cerr << "Error: No value supplied for the non-option argument "
-                     "\"config\".\n";
-        return mqbu::ExitCode::e_COMMAND_LINE;  // RETURN
-    }
+        if (configDir.empty()) {
+            bsl::cerr << "Error: No value supplied for the non-option "
+                         "argument \"config\".\n";
+            return mqbu::ExitCode::e_COMMAND_LINE;  // RETURN
+        }
+    }  // specTable and commandLine are destroyed here
```
Comment (678098) [inline src/applications/bmqbrkr/bmqbrkr.m.cpp:670]:
```suggestion
    }  // specTable and commandLine are destroyed here

    if (version) {
        bsl::cout << "BlazingMQ broker version: "
                  << bmqbrkrscm::Version::version() << "\n";
        return 0;
    }

    if (configDir.empty()) {
        bsl::cerr << "Error: No value supplied for the non-option "
                     "argument \"config\".\n";
        return mqbu::ExitCode::e_COMMAND_LINE;  // RETURN
    }
```
By the way, it is possible to move `specTable` scope exit a bit earlier.
This removed indentation changes to these few lines, making the PR more compact.
In general, it is always good to have the minimal change.
Also, there is a good principle: if there is no reason to change something, don't change it. These checks were just fine without being in another scope, so there is no reason to move them in this scope.

This is a small comment and we can still merge it

**Review by 678098 — APPROVED** [review]

**Comment by 678098** [comment]
Hi @SrinathhSatuluri, going to merge the PR.
Thank you for the contribution!

>Regarding taskEnv still taking a lot of space, would you like me to address that in this PR before merging, or should we track it as a separate follow-up issue?

This one can be done in another PR

**Comment by SrinathhSatuluri** [comment]
Thankyou for the guidance! @678098. I'll open a follow-up issue for the taskEnv stack usage.
