### PR TITLE
Fix[storagetool] Fix csl file relative path handling

### LINKED ISSUE #955: bmqstoragetool: handle local storage files
Running storage tool from the storage directory with filepath arg fails:

```
./bmqstoragetool.tsk -- --csl-file bmq_csl_20250724_182936_951297D55F.bmq_csl
Open ledger failed with error: -2
```

It only works if the provided path contains at least one `/`:

```
lldb ./bmqstoragetool.tsk -- --csl-file ./bmq_csl_20250724_182936_951297D55F.bmq_csl
```

The correct way is to convert the provided path to absolute and deduce the current directory with it.

### PR DESCRIPTION
**Pull request by alexander-e1off**
Closes #955 

Csl file handling is different from journal/data/qlist, because it is passed by parts (pattern, location) into `LedgerConfig`.
Changed csl path handling as follows: if `location` is empty, set explicitly current directory `"."`.

Manually tested:
```
./bmqstoragetool.tsk --csl-file bmq_csl_20241029_140023_87EDF15DC0.bmq_csl
./bmqstoragetool.tsk --csl-file ./bmq_csl_20241029_140023_87EDF15DC0.bmq_csl
./bmqstoragetool.tsk --csl-file ../bmq_csl_20241029_140023_87EDF15DC0.bmq_csl
./bmqstoragetool.tsk --csl-file <absolute_path>/bmq_csl_20241029_140023_87EDF15DC0.bmq_csl

./bmqstoragetool.tsk --journal-file bmq_0.20241029_140023.bmq_journal
```

### CODE REVIEW

File: src/applications/bmqstoragetool/m_bmqstoragetool_filemanager.cpp [hunk 1]
```diff
@@ -245,6 +245,11 @@ bool FileManagerImpl::CslFileHandler::resetIterator(
         return false;  // RETURN
     }
 
+    // If `location` is empty, use explicitly current directory.
```
Comment (678098) [inline src/applications/bmqstoragetool/m_bmqstoragetool_filemanager.cpp]:
```suggestion
    // Use current directory when `location` is empty.
```

**Review by 678098 — COMMENTED** [review]
Thanks @alexander-e1off!
Have one small comment, I think rephrasing will sound slightly better

File: src/applications/bmqstoragetool/m_bmqstoragetool_filemanager.cpp (hunk 1 above)
Comment (alexander-e1off) [reply src/applications/bmqstoragetool/m_bmqstoragetool_filemanager.cpp]: Agree, updated as proposed.

Comment (678098) [reply src/applications/bmqstoragetool/m_bmqstoragetool_filemanager.cpp]: Thanks!
